---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isoqgdmy/public_html/asahorvitz.com/laumasite/ghost
    - rm -rf $DEPLOYPATH
    - mkdir $DEPLOYPATH
    - /bin/cp -a src $DEPLOYPATH
    - /bin/cp -a public $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp babel.config.json $DEPLOYPATH
    - /bin/cp procemon.sh $DEPLOYPATH
    - cd $DEPLOYPATH
    - chmod -x procemon.sh
    - TZ='Europe/London' date >> setup.log
    - npm i >> setup.log 2>&1
    - TZ='Europe/London' date >> setup.log
    - npm run build >> setup.log 2>&1
    - TZ='Europe/London' date >> serve.log 2>&1
    - bash procemon.sh >> serve.log 2>&1
