---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isoqgdmy/public_html/asahorvitz.com/laumasite/ghost_ai
    - rm -rf $DEPLOYPATH
    - mkdir $DEPLOYPATH
    - /bin/cp -a src $DEPLOYPATH
    - /bin/cp -a public $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp babel.config.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - TZ='Europe/London' date >> i_out.txt
    - npm i >> i_out.txt 2>&1
    - TZ='Europe/London' date >> run_build_out.txt
    - npm run build >> run_build_out.txt
    - TZ='Europe/London' date >> serve_out.txt 2>&1
    - serve -s build -p 443 >> serve_out.txt 2>&1
