---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isoqgdmy/public_html/asahorvitz.com/laumasite/ghost
    - rm -rf $DEPLOYPATH
    - mkdir $DEPLOYPATH
    - /bin/cp -a src $DEPLOYPATH
    - /bin/cp -a public $DEPLOYPATH
    - /bin/cp -a assets $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp babel.config.json $DEPLOYPATH
    - /bin/cp home.html $DEPLOYPATH
    - cd $DEPLOYPATH
    - TZ='Europe/London' date >> setup.log
    - npm i >> setup.log 2>&1
    - TZ='Europe/London' date >> setup.log
    - npm run build >> setup.log 2>&1
    - mv aisystem/index.html aisystem/home.html
