---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isoqgdmy/public_html/asahorvitz.com/laumasite/ghost_ai
    - rm -rf $DEPLOYPATH
    - mkdir $DEPLOYPATH
    - /bin/cp -a src $DEPLOYPATH
    - /bin/cp -a public $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm i >> i_out.txt
    - npm run build >> run_build_out.txt
    - serve -s build >> serve_out.txt
