---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isoqgdmy/public_html/asahotvitz.com/ghost_ai
    - git fetch & git pull
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm i
    - npm run build
