---
deployment:
  tasks:
    - export DEPLOYPATH=/home/isoqgdmy/public_html/asahorvitz.com/laumasite/ghost_ai
    - mkdir $DEPLOYPATH
    - /bin/cp -a src $DEPLOYPATH
    - /bin/cp -a public $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm i
    - npm run build
    - serve -s build
